spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 129.204.79.202
    password: 123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: test
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
mybatis:
  mapper-locations : classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8087
  servlet:
    context-path: /ende
